spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:h2:tcp://localhost/C:/Users/user/Desktop/studyDB/h2_prac/mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
